import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import WhatsAppSupport from "@/components/WhatsAppSupport";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "sonner"; 
import Script from "next/script";
import { Inter as NextInter } from "next/font/google";
import { Lato as NextLato } from "next/font/google";

// Load Inter for headings & buttons
const inter = NextInter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-inter",
});

// Load Lato for body text
const lato = NextLato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} ${lato.variable} antialiased bg-background text-foreground transition-colors duration-300`}
      >
        {/* Paystack Script */}
        <Script
          src="https://js.paystack.co/v1/inline.js"
          strategy="beforeInteractive"
        />

        <CartProvider>
          <Navbar />
          {children}
          <Footer />
          <WhatsAppSupport />
        </CartProvider>

        {/* Sonner Toaster */}
        <Toaster
          closeButton
          position="bottom-right"
          duration={2000}
          toastOptions={{
            className:
              "max-md:!left-1/2 max-md:!transform max-md:!-translate-x-1/2 max-md:!right-auto",
          }}
        />
      </body>
    </html>
  );
}
